joy:
  ros__parameters:
    device_id: 0
#    device_name: /dev/input/js0
    deadzone: 0.01
    autorepeat_rate: 20.0
    coalesce_interval: 0.01

joy_teleop:
  ros__parameters:
    default:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: teleop
      axis_mappings:
        drive-speed:
          axis: 1
          scale: 0.0
          offset: 0.0
        drive-steering_angle:
          axis: 2
          scale: 0.0
          offset: 0.0

    human_control:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: teleop
      deadman_buttons: [7]
      axis_mappings:
        drive-speed:
          axis: 1
          scale: 1.5
          offset: 0.0
        drive-steering_angle:
          axis: 3  
          scale: 0.34
          offset: 0.0

    autonomous_control:
      type: topic
      interface_type: std_msgs/msg/Int8
      topic_name: /dev/null
      deadman_buttons: [5]
      message_value:
        data:
          value: 0
    
    safe_break_reset:
      type: topic
      interface_type: std_msgs/msg/Bool
      topic_name: /reset_safe_brake
      deadman_buttons: [3]
      message_value:
        data:
          value: true
